controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_home_redirect:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::class
  defaults:
    route: app_login